title: Package
description: The declaration to install a package.
payload:
  declarationtype: com.apple.configuration.package
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '26.0'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  apply: multiple
payloadkeys:
- key: ManifestURL
  title: Manifest URL
  type: <string>
  presence: required
  content: The URL of the manifest document for the package that the device downloads.
    The manifest is returned as a `ManifestURL` property list. The `url` property
    of the manifest must point to the package (.pkg) file to install.
- key: InstallBehavior
  title: Install Behavior
  type: <dictionary>
  presence: optional
  content: A dictionary that describes how and when to install the package.
  subkeys:
  - key: Install
    title: Install
    type: <string>
    presence: optional
    rangelist:
    - Optional
    - Required
    default: Optional
    content: |-
      A string that specifies when the system installs the package:

      - `Optional`: The user can install the package after the system activates the configuration.
      - `Required`: The system installs the package after it activates the configuration.
notes:
- title: ''
  content: This declaration installs a package on a device. Packages can contain apps,
    fonts, documents, and other items. Apps that a package installs aren't automatically
    managed; you can manage them using the `AppManaged` declaration.
