title: Screen Sharing:Host Settings
description: The declaration to configure screen-sharing host settings and restrictions.
payload:
  declarationtype: com.apple.configuration.screensharing.host.settings
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '14.0'
      allowed-enrollments:
      - supervised
      - local
      allowed-scopes:
      - system
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  apply: single
payloadkeys:
- key: MaximumVirtualDisplays
  title: Maximum number of Virtual Displays
  type: <integer>
  presence: optional
  range:
    min: 0
    max: 2
  content: The maximum number of virtual displays to make available to clients.
- key: PortBase
  title: UDP Port base
  type: <integer>
  presence: optional
  range:
    min: 1024
    max: 65535
  content: The initial UDP port number to connect to the host. Screen sharing requires
    multiple connections, so the system increments this value by 1 for each additional
    connection. This doesn't change the port number that the system uses to initially
    establish a connection with a host, which is always TCP port 5900.
- key: PreventCopyFilesFromHost
  title: Prevent copying files from host
  type: <boolean>
  presence: optional
  default: false
  content: If `true`, the system prevents users from copying files from the screen-sharing
    host.
- key: PreventCopyFilesToHost
  title: Prevent copying files to host
  type: <boolean>
  presence: optional
  default: false
  content: If `true`, the system prevents users from copying files to the screen-sharing
    host.
- key: PreventHighPerformanceConnections
  title: Prevent High Performance connections
  type: <boolean>
  presence: optional
  default: false
  content: If `true`, the system prevents clients from establishing high-performance
    connections to the host.
