scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zentral_inventory'
    metrics_path: '/metrics/inventory/'
    bearer_token: 'CHANGE ME!!!'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'zentral_munki'
    metrics_path: '/metrics/munki/'
    bearer_token: 'CHANGE ME!!!'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'zentral_santa'
    metrics_path: '/metrics/santa/'
    bearer_token: 'CHANGE ME!!!'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'zentral_workers'
    file_sd_configs:
      - files:
          - '/prometheus_sd/workers.yml'
